services:
  postgres:
    image: postgres:16
    container_name: postgres-phishing
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d phishing_detect" ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: redis-phishing
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20

  # Orquestador Principal
  orchestrator:
    build:
      context: ./services/srv-orchestrator
      dockerfile: Dockerfile
    container_name: srv-orchestrator
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  # Servicio de Conocimiento (RAG)
  knowledge-rag:
    build:
      context: ./services/srv-knowledge-rag
      dockerfile: Dockerfile
    container_name: srv-knowledge-rag
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file: .env

  # Servicio de Reputación (CU-03)
  reputation:
    build:
      context: ./services/CU-03
      dockerfile: Dockerfile
    container_name: srv-reputation
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file: .env

  # Interfaz Web (Frontend)
  chatbot-ui:
    build:
      context: ./frontends/fnd-chatbot
      dockerfile: Dockerfile
    container_name: fnd-chatbot
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - orchestrator

  # interfaz web para ver la BD
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-phishing
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
